// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require("chromedriver")

describe('test timothee nourris', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test timothee nourris', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1268, height: 660 })
    await driver.findElement(By.linkText("Add")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("test timothee")
    await driver.findElement(By.id("description")).sendKeys("test by timothee nourris")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})
// record en cliquand sur sa task a la fin, ensuite prendre le derniere case et remplacer le css = par le dernier choix
// ensuite enleber le click de la derniere ligne et mettre un s a element's'